#!/bin/sh
wget    -P amicorpus/TS3003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003a/audio/TS3003a.Mix-Headset.rm
wget    -P amicorpus/TS3003b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003b/audio/TS3003b.Mix-Headset.rm
wget    -P amicorpus/TS3003c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003c/audio/TS3003c.Mix-Headset.rm
wget    -P amicorpus/TS3003d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003d/audio/TS3003d.Mix-Headset.rm
wget    -P amicorpus/TS3004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004a/audio/TS3004a.Mix-Headset.rm
wget    -P amicorpus/TS3004b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004b/audio/TS3004b.Mix-Headset.rm
wget    -P amicorpus/TS3004c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004c/audio/TS3004c.Mix-Headset.rm
wget    -P amicorpus/TS3004d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004d/audio/TS3004d.Mix-Headset.rm
wget    -P amicorpus/TS3005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005a/audio/TS3005a.Mix-Headset.rm
wget    -P amicorpus/TS3005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005b/audio/TS3005b.Mix-Headset.rm
wget    -P amicorpus/TS3005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005c/audio/TS3005c.Mix-Headset.rm
wget    -P amicorpus/TS3005d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005d/audio/TS3005d.Mix-Headset.rm
wget    -P amicorpus/TS3006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006a/audio/TS3006a.Mix-Headset.rm
wget    -P amicorpus/TS3006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006b/audio/TS3006b.Mix-Headset.rm
wget    -P amicorpus/TS3006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006c/audio/TS3006c.Mix-Headset.rm
wget    -P amicorpus/TS3006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006d/audio/TS3006d.Mix-Headset.rm
wget    -P amicorpus/TS3007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007a/audio/TS3007a.Mix-Headset.rm
wget    -P amicorpus/TS3007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007b/audio/TS3007b.Mix-Headset.rm
wget    -P amicorpus/TS3007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007c/audio/TS3007c.Mix-Headset.rm
wget    -P amicorpus/TS3007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007d/audio/TS3007d.Mix-Headset.rm
wget    -P amicorpus/TS3008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008a/audio/TS3008a.Mix-Headset.rm
wget    -P amicorpus/TS3008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008b/audio/TS3008b.Mix-Headset.rm
wget    -P amicorpus/TS3008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008c/audio/TS3008c.Mix-Headset.rm
wget    -P amicorpus/TS3008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008d/audio/TS3008d.Mix-Headset.rm
wget    -P amicorpus/TS3009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009a/audio/TS3009a.Mix-Headset.rm
wget    -P amicorpus/TS3009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009b/audio/TS3009b.Mix-Headset.rm
wget    -P amicorpus/TS3009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009c/audio/TS3009c.Mix-Headset.rm
wget    -P amicorpus/TS3009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009d/audio/TS3009d.Mix-Headset.rm
wget    -P amicorpus/TS3010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010a/audio/TS3010a.Mix-Headset.rm
wget    -P amicorpus/TS3010b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010b/audio/TS3010b.Mix-Headset.rm
wget    -P amicorpus/TS3010c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010c/audio/TS3010c.Mix-Headset.rm
wget    -P amicorpus/TS3010d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010d/audio/TS3010d.Mix-Headset.rm
wget    -P amicorpus/TS3011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011a/audio/TS3011a.Mix-Headset.rm
wget    -P amicorpus/TS3011b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011b/audio/TS3011b.Mix-Headset.rm
wget    -P amicorpus/TS3011c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011c/audio/TS3011c.Mix-Headset.rm
wget    -P amicorpus/TS3011d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011d/audio/TS3011d.Mix-Headset.rm
wget    -P amicorpus/TS3012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012a/audio/TS3012a.Mix-Headset.rm
wget    -P amicorpus/TS3012b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012b/audio/TS3012b.Mix-Headset.rm
wget    -P amicorpus/TS3012c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012c/audio/TS3012c.Mix-Headset.rm
wget    -P amicorpus/TS3012d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012d/audio/TS3012d.Mix-Headset.rm
wget https://groups.inf.ed.ac.uk/ami/download/temp/../CCBY4.0.txt
